#!/usr/bin/python

import sys
import subprocess as sp
import numpy as np

if len(sys.argv) not in [4, 5]: # 5 means not using idx
    print(f"Usage : {sys.argv[0]} <input bin> <input idx> <output vid>")
    print(f"  e.g., {sys.argv[0]} data/video0.bin result0.out result0.mp4")
    sys.exit(1)

FFMPEG_BIN = "/scratch/share/apss17/vr_data/ffmpeg"

with open(sys.argv[2]) as fidx:
    idxs = map(int, fidx.read().splitlines())

N = len(idxs)
H = 1080
W = 1920
C = 3

if len(sys.argv) == 5:
    idxs = range(N)

command = [
    FFMPEG_BIN,
    '-y',
    '-f',
    'rawvideo',
    '-vcodec',
    'rawvideo',
    '-s',
    f'{W}x{H}',
    '-pix_fmt',
    'rgb24',
    '-r',
    '30',
    '-i',
    '-',
    '-an',
    '-vcodec',
    'mpeg4',
    sys.argv[3],
]

pipe = sp.Popen( command, stdin=sp.PIPE)

with open(sys.argv[1], "rb") as fbin:
    rawvideo = fbin.read()
    for idx in idxs:
        pipe.stdin.write(rawvideo[idx * H * W * C : (idx + 1) * H * W * C])
